# 使用 Node.js 20 镜像
FROM node:20.12.2

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json 到容器中
COPY ./package*.json ./

# 设置淘宝镜像源
RUN npm config set registry https://registry.npmmirror.com

# 安装依赖
RUN npm install

# 复制所有文件
COPY . .

# 暴露前端服务的端口
EXPOSE 3000

# 启动前端服务
CMD ["npm", "start"]
